#! /bin/bash

# run this script as "top10 log.txt"
grep -e 'HTTP/1.1" 4' -e 'HTTP/1.0" 4' log.txt | cut -f11 -d" "| grep -v '"-"' | sort -t" " -k1 | uniq -c | sort --reverse -k1 -n | head|awk '{ t=$1 ; $1=$2; $2=t; print }' | awk '{a[NR] = $2;b[NR]=$1; sum+=$2}END{for(i=1;i<=NR;i++) printf "%s - %s - %s%%\n",b[i],a[i],100*a[i]/sum}'
# here comes your solution
# e.g.
grep world $1
